spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edge
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    ignore-unsupported-database: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
  endpoint:
    flyway:
      enabled: true
